<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_63e1151a7e7d6',
        'title' => 'Dynamic Inputs',
        'fields' => array(
            array(
                'key' => 'field_63e1151ace45d',
                'label' => 'Dynamic Inputs',
                'name' => 'dynamic_inputs',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Row',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_63e115c5d9152',
                        'label' => 'Input Type',
                        'name' => 'input_type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'text' => 'Single line',
                            'textarea' => 'Multiple lines',
                            'select' => 'List of options',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                    array(
                        'key' => 'field_63e1164cd9153',
                        'label' => 'Label',
                        'name' => 'label',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                    array(
                        'key' => 'field_63e1165ad9154',
                        'label' => 'Name',
                        'name' => 'name',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                    array(
                        'key' => 'field_63e11668d9155',
                        'label' => 'Placeholder',
                        'name' => 'placeholder',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_63e115c5d9152',
                                    'operator' => '==',
                                    'value' => 'text',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_63e115c5d9152',
                                    'operator' => '==',
                                    'value' => 'textarea',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                    array(
                        'key' => 'field_63e11681d9156',
                        'label' => 'Required',
                        'name' => 'required',
                        'aria-label' => '',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'required' => 'required',
                            'not-required' => 'not-required',
                        ),
                        'default_value' => '',
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'layout' => 'vertical',
                        'save_other_choice' => 0,
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                    array(
                        'key' => 'field_63e116acd9157',
                        'label' => 'Select Options',
                        'name' => 'select_options',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => 'Please enter values separated by | (Option 1 | Option 2 | Option 3)',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_63e115c5d9152',
                                    'operator' => '==',
                                    'value' => 'select',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'field_63e1151ace45d',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'master-form.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;
